project_id = "cthqzetkshrbsjulfytl"

[functions.pix-payment]
verify_jwt = false

[functions.scratch-card-play]
verify_jwt = false

[functions.lzt-market]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.generate-game-image]
verify_jwt = false

[functions.track-login]
verify_jwt = false

[functions.server-relay]
verify_jwt = true

[functions.robot-project]
verify_jwt = false
