/** Aliases de jogos: partilhado entre `src/lib/gameSlug.ts` e `pix-payment`. */
export const GAME_SLUG_ALIASES: Record<string, string> = {
  "counter strike 2": "cs2",
  "counter-strike 2": "cs2",
  "counter-strike-2": "cs2",
  "counter-strike 2 (free)": "cs2",
  "counter strike 2 free": "cs2",
  "counter-strike-2-free": "cs2",
  "cs2 free": "cs2",
  "cs2-free": "cs2",
  cs2: "cs2",
  "call of duty": "cod",
  "call-of-duty": "cod",
  cod: "cod",
  "arena breakout infinite": "arena-breakout-infinite",
  "arena-breakout-infinite": "arena-breakout-infinite",
  "arc raiders": "arc-raiders",
  "arc-raiders": "arc-raiders",
  "apex legends": "apex-legends",
  "apex-legends": "apex-legends",
  "overwatch 2": "overwatch-2",
  "overwatch-2": "overwatch-2",
  "marvel rivals": "marvel-rivals",
  "marvel-rivals": "marvel-rivals",
  "dead by daylight": "dead-by-daylight",
  "dead-by-daylight": "dead-by-daylight",
  "hell let loose": "hell-let-loose",
  "hell-let-loose": "hell-let-loose",
  pubg: "pubg",
  bloodstrike: "bloodstrike",
  "farlight 84": "farlight-84",
  "farlight-84": "farlight-84",
  bodycam: "bodycam",
  warface: "warface",
  spoofers: "spoofers",
  squad: "squad",
  bloodhunt: "bloodhunt",
  fivem: "fivem",
  dayz: "dayz",
  rust: "rust",
  valorant: "valorant",
  /** LZT / Riot client — listagens Valorant usam `riot` como game_type. */
  riot: "valorant",
  fortnite: "fortnite",
  minecraft: "minecraft",
  brawlstars: "brawlstars",
  "brawl-stars": "brawlstars",
  "brawl stars": "brawlstars",
  lol: "lol",
  /** Títulos LZT / vitrine — sem isto o Pixel manda `league-of-legends` e a conversão "IC - Contas - LoL" (lol) nunca casa. */
  "league of legends": "lol",
  "league-of-legends": "lol",
  "league-of-legends-account": "lol",
  "fortnite battle royale": "fortnite",
  "fortnite-battle-royale": "fortnite",
  "minecraft java": "minecraft",
  "minecraft-java": "minecraft",
  "minecraft bedrock": "minecraft",
  "minecraft-bedrock": "minecraft",
  produto: "produto",
  multi: "multi",
};
